export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';

export const PROVIDER_ADDED = 'PROVIDER_ADDED';
export const CANCEL_ADD_PROVIDER = 'CANCEL_ADD_PROVIDER';
export const SHOW_PROVIDER_ADD_MODAL = 'SHOW_PROVIDER_ADD_MODAL';
export const SELECT_PROVIDER = 'SELECT_PROVIDER';
export const INPUT_API_KEY = 'INPUT_API_KEY';
export const REMOVE_PROVIDER = 'REMOVE_PROVIDER';
export const TEST_REQUEST = 'TEST_REQUEST';
export const TEST_ACCEPTED = 'TEST_ACCEPTED';
export const TEST_REJECTED = 'TEST_REJECTED';

export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_LOADING_FAILED = 'PROJECTS_LOADING_FAILED';
export const PROJECTS_LOADED = 'PROJECTS_LOADED';

export const BRANCHES_LOADED = 'BRANCHES_LOADED'
export const BRANCHES_LOADING = 'BRANCHES_LOADING'

export const BUILDS_LOADED = 'BUILDS_LOADED'
export const BUILDS_LOADING = 'BUILDS_LOADING'
