export const DATA_FETCHED = 'DATA_FETCHED';
export const DATA_SUCCEEDED = 'DATA_SUCCEEDED';
export const DATA_FAILED = 'DATA_FAILED';

export const PROVIDER_ADDED = 'PROVIDER_ADDED';
export const SHOW_PROVIDER_ADD_MODAL = 'SHOW_PROVIDER_ADD_MODAL';
export const SELECT_PROVIDER = 'SELECT_PROVIDER';